#!/bin/bash

clear                                 

echo -n "          "
echo -e '\E[37;44m'"\033[1mTroubleshoot\033[0m"
my_dir="$(dirname "$0")"

echo;echo

# Get domainname
domain=$1

# Variables
var1=$domain
var8=Domeinnaam
var11=Automate


## Get IP-adres
function system_info {
        dig a $domain +short
} 
var2="$(system_info)"

## Get PTR-record of IP-adres
function ptr {
dig -x $(system_info) +short 
}
var3=$(ptr)

## Get the nameserves of domainname
function nameserver { 
	dig ns $domain +short
} 
 
# If-statement for the nameservers
if [[ $(nameserver) ]] 
  then 
     var4="$(nameserver)"
  else 
     var4="Geen Nameservers gevonden voor $domain"
fi

## Get MX-record of domainname 
function mailrecord {
dig mx $domain +short
} 

# IF-statement for the MX-record
if [[ $(mailrecord) ]] 
  then 
   var5="$(mailrecord)"
  else 
   var5="Geen MX-record gevonden voor $domain"
fi 

## Get automate-result
function automate { 
    curl -s 'http://automate.hostnetbv.nl/spam.php' -H 'Origin: http://automate.hostnetbv.nl' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://automate.hostnetbv.nl/spam.php' -H 'Connection: keep-alive' --data 'domainname='$domain'&check=Check+Destination' --compressed | grep "<h3><pre>" | cut -c 10-
    
    }

## Store result function automate
var6=$(automate) 
  

## IP-range check
### Needs to be changed to WHOIS IP-adres | grep netname
function iprange { exec "$my_dir/iprangecheck" $(system_info) | grep "is in"
}

## IF-statement for IP-range check 
if [[ $(iprange) ]] ; 
  then 
     var7="IP-adres valt binnen range van Hostnet"
  else 
    var7="IP-adres valt niet binnen range van Hostnet"
fi 

# The inserted domainname 
echo -en 'De ingevoerde domeinnaam: '  '\E[47;31m'"\033[1m$domain\033[0m"

echo;echo

## The found output for the functions
printf '%s\t%s\n' \
  Input Output \
  "$var8" "$var1" \
  "IP-adres" "$var2" \
  "PTR" "$var3" \ | 
   column -t -s $'\t' 
echo
echo MX-record
echo $var5
echo 
echo Automate-check
echo $var6 
echo 
echo Nameservers 
echo $var4
echo 
echo IP-rangecheck
echo $var7
