#!/bin/bash

clear                                 

echo -n "          "
echo -e '\E[37;44m'"\033[1mTroubleshoot\033[0m"
                                        
echo; echo

##funtie één ipadress ophalen
function system_info {
dig  $domain +short
}

#########################

#foutieve code 

#function nameserver {
#dig ns 


#funtion getIpAdress { 
#dig $domain +short 
#}
###########################

# Get domainname
domain=$1
echo -en 'De ingevoerde domeinnaam: '  '\E[47;31m'"\033[1m$domain\033[0m"

echo '      '
echo '      ' 

## IP-adress achterhalen
# ipadress= dig $domain +short
echo -en 'Het gevonden IP-adress: ' '\E[47;31m'"\033[1m$(system_info)\033[0m"


echo; echo   #witregel


## PTR-record
function ptr {
dig -x $(system_info) +short 
}
echo 'PTR-record wijst naar : '$(ptr)
echo
 

## Nameservers bepalen
echo 'De nameservers van '$domain' zijn als volgt:'
nameserver= dig ns $domain +short
echo $nameserver

echo; echo #witregel

#mxrecord indien aanwezig
function mailrecord {
dig mx $domain +short
} 
echo 'De volgende mx-record(s) is/zijn gevonden: '

echo -e $(mailrecord)
echo; echo

function automate { 

curl -s 'http://automate.hostnetbv.nl/spam.php' -H 'Origin: http://automate.hostnetbv.nl' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://automate.hostnetbv.nl/spam.php' -H 'Connection: keep-alive' --data 'domainname='$domain'&check=Check+Destination' --compressed | grep "<h3><pre>" | cut -c 10-
} 
echo 'Dit is het resultaat uit automate: ' $(automate) 






